### ISSUE TITLE
注册流程改进一部，可以省钱

### ISSUE THREAD

**Issue by X-Bird** [makeflow/makeflow#14]
`应该在这一步的时候直接检测手机没被注册过才能进入下一步`
`要不进入下一步的时候短信验证码就发出去了，浪费一条短信`
`而且用户只才能在第二步才知道自己手机号被注册了`
![image](https://user-images.githubusercontent.com/1308295/68728163-85ef2e00-0601-11ea-8f1f-774f22145b88.png)

**Comment by vilicvane** [comment]
这个是出于安全考虑，避免非手机拥有人嗅探
