### ISSUE TITLE
关于邀请已经注册过的成员遇到的问题

### ISSUE THREAD

**Issue by X-Bird** [makeflow/makeflow#15]
1. 用户A注册
2. 用户B注册
3. 用户A生成邀请链接
4. 用户B在登陆状态下打开链接
5. 弹出的是注册框，不解
6. 用户A看不到用户B
7. 用户A在 【组织设置】-> 【组织管理】 中点＋号，可以看到成员列表里面有用户B名字，于是点击用户B名字，提示：是否什么更改管理员列表。
8. 点击是，成员管理里面就有两个人了
9. 用户A新建任务，分配给B，B收不到，卡住到这里

**Comment by X-Bird** [comment]
#### UPDATE: 发现问题了
* 用户B没有成功加入A的组织
* 用户B已经登陆情况下建议打开邀请链接就不要再让登陆了

**Comment by vilicvane** [comment]
![image](https://user-images.githubusercontent.com/970430/71373087-fd48b200-25f0-11ea-98ec-96700111d6cd.png)
