### ISSUE TITLE
组织管理列表里的成员能增不能减？

### ISSUE THREAD

**Issue by X-Bird** [makeflow/makeflow#16]
* 组织设置 -> 组织管理 -> 成员列表页里面的成员只能+不能减，没发现删除操作

**Comment by vilicvane** [comment]
![image](https://user-images.githubusercontent.com/970430/71371828-79d99180-25ed-11ea-9eb8-50fd2c6cad72.png)
之前其实是可以的，不过用的是加号。这个版本加号改成了省略号
