### ISSUE TITLE
流程节点设置展示条件后，能否在流程图上直观地展示出该节点是有条件展示的

### ISSUE THREAD

**Issue by YianAndCode** [makeflow/makeflow#18]
例如：

![image](https://user-images.githubusercontent.com/6998693/68738742-0faef380-0622-11ea-9d17-45ec28791a94.png)

![image](https://user-images.githubusercontent.com/6998693/68738778-22c1c380-0622-11ea-9f99-9a9541dff894.png)

设置了展示条件后，跟普通节点还是长得一样，建议将条件展示出来，或者有展示条件的节点采用不同的颜色

**Comment by vilicvane** [comment]
![image](https://user-images.githubusercontent.com/970430/71371699-fc158600-25ec-11ea-9d98-587bea8566c8.png)
![image](https://user-images.githubusercontent.com/970430/71371708-0172d080-25ed-11ea-9e81-52f6fa0a3ca2.png)
